bump_version: null
lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - .github/ISSUE_TEMPLATE/config.yml
    - assets/nf-core-genepal_logo_light.png
    - docs/images/nf-core-genepal_logo_light.png
    - docs/images/nf-core-genepal_logo_dark.png
    - tests/default.nf.test
  files_unchanged:
    - .gitignore
    - LICENSE
    - .github/workflows/branch.yml
    - .github/workflows/linting.yml
    - docs/README.md
  included_configs: false
  multiqc_config: false
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - config_defaults:
        - params.ribo_database_manifest
  nf_test_content:
    - tests/default.nf.test
    - tests/nextflow.config
nf_core_version: 3.3.1
repository_type: pipeline
template:
  author: Usman Rashid, Jason Shiller
  description: A Nextflow pipeline for consensus, phased and pan-genome annotation.
  force: false
  is_nfcore: false
  name: genepal
  org: plant-food-research-open
  outdir: .
  skip_features:
    - igenomes
  version: 1.0.0dev
