# Adopted from https://github.com/nf-core/modules/blob/master/.github/workflows/test.yml

name: Lint and -stub on Linux/Docker
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Cancel if a newer run is started
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: "pip"

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files

  stub-test:
    runs-on: ubuntu-latest
    name: Run stub test with docker
    env:
      NXF_ANSI_LOG: false

    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: PlantandFoodResearch/pangene-test
          ssh-key: ${{ secrets.PANGENE_TEST_DEPLOY_KEY }}
          path: pangene-test

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "23.04.4"

      - name: Run stub-test
        run: |
          nextflow \
            main.nf \
            -profile local,docker \
            -resume \
            -stub \
            -c conf/test_stub.config

  confirm-pass:
    runs-on: ubuntu-latest
    needs: [pre-commit, stub-test]
    if: always()
    steps:
      - name: All tests ok
        if: ${{ success() || !contains(needs.*.result, 'failure') }}
        run: exit 0
      - name: One or more tests failed
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1

      - name: debug-print
        if: always()
        run: |
          echo "toJSON(needs) = ${{ toJSON(needs) }}"
          echo "toJSON(needs.*.result) = ${{ toJSON(needs.*.result) }}"
